### ISSUE TITLE
建议再增加一些功能

### ISSUE THREAD

**Issue by chunipo** [rogerzhu/NBAsh#3]
增加一个查看实时评论，可以显示，可以隐藏开关；
是否可以加一个刷新数据时画面保持静止的功能，不然一直刷容易被发现～～

**Comment by rogerzhu** [comment]
一个刷新数据时画面保持静止的功能-->在我从内部库和外部设计深入研究了几天后，这个有眉目了，应该很快就会更新个新版本
实时评论 --> 怕被虎扑封了，等我扩展几个源再做这个

**Comment by chunipo** [comment]
实时评论可以考虑拉其他平台也行～

**Comment by rogerzhu** [comment]
> 实时评论可以考虑拉其他平台也行～

这样一说 可以考虑 哈哈 大不了封了评论的 看球的功能还有

**Comment by chunipo** [comment]
> > 实时评论可以考虑拉其他平台也行～
> 
> 这样一说 可以考虑 哈哈 大不了封了评论的 看球的功能还有

是呀，哈哈
